#!/usr/bin/env bash
# sync_to_pocket.sh — vendor the canonical Dr. Mario copro RTL into the Analogue Pocket tree.
#
# Canonical source = THIS directory (dr-mario-mods/fpga/copro). One source of truth; both the
# MiSTer mapper (NES_MiSTer/rtl/mappers) and the Pocket core vendor FROM here — no divergent copies.
#
# Vendors the SYNTHESIS set only into  <pocket>/target/pocket/vendor/copro/  with a DO-NOT-EDIT +
# source-commit header, and (re)generates copro.qip. Idempotent (header date only moves when a file's
# body changes) and diff-printing. Does NOT touch rtl/upstream/ or projects/ (safe during a fit run).
#
# Deliberately EXCLUDED:
#   dpram.v      -> sim-only stub; the real build binds CoproDrMario's `dpram` to agg23's
#                   rtl/upstream/dpram.vhd, which is byte-identical to MiSTer's (same entity/generics).
#                   Vendoring ours would create a duplicate-module collision. See portability audit.
#   cpu.v, ALU.v -> original Arlet Ottens core; superseded by the namespaced copro6502 / copro_alu.
#   tb.v top_v.v top_iface.v sim_*.cpp -> verilator/iverilog harness, not synthesized.
#
# Usage:  ./sync_to_pocket.sh [DEST_DIR]
#   DEST_DIR defaults to the Pocket worktree's vendor dir. Pass a scratch dir for a dry preview.
set -euo pipefail

# SRC defaults to this script's dir (the canonical copro source); override with COPRO_SRC for testing.
SRC="${COPRO_SRC:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
DST="${1:-/home/struktured/projects/pocket-nes-mapper100/target/pocket/vendor/copro}"

RTL=(CoproDrMario.sv LeafEval.sv copro6502.v copro_alu.v)   # order irrelevant; Quartus resolves
HEX=copro_rom.hex

# --- preflight: Pocket instantiates CoproDrMario #(.WIN(...)); the canonical must be parameterized.
if ! grep -qE 'parameter *\[6:0\] *WIN' "$SRC/CoproDrMario.sv"; then
  echo "ERROR: $SRC/CoproDrMario.sv is NOT parameterized (#(.WIN(...)))." >&2
  echo "       The Pocket cart.sv instantiates CoproDrMario #(.WIN(7'b0101_000))." >&2
  echo "       Promote the parameterized form to canonical first" >&2
  echo "       (NES_MiSTer/rtl/mappers/CoproDrMario.sv is the deployed parameterized version)." >&2
  exit 2
fi

HASH="$(git -C "$SRC" rev-parse --short HEAD 2>/dev/null || echo nogit)"
git -C "$SRC" diff --quiet HEAD 2>/dev/null || HASH="${HASH}-dirty"   # flag uncommitted canonical
STAMP="// AUTO-VENDORED from dr-mario-mods/fpga/copro @ ${HASH} ($(date -u +%FT%TZ)) -- DO NOT EDIT HERE."
NOTE="// Edit the canonical source in dr-mario-mods/fpga/copro and re-run sync_to_pocket.sh."

mkdir -p "$DST"
changed=0

vendor_one() {  # $1 = filename
  local f="$1" src="$SRC/$1" dst="$DST/$1" tmp
  tmp="$(mktemp)"
  printf '%s\n%s\n' "$STAMP" "$NOTE" > "$tmp"
  cat "$src" >> "$tmp"
  # compare bodies (skip the 2 header lines) so the date stamp alone never forces a rewrite
  if [ -f "$dst" ] && diff -q <(tail -n +3 "$dst") "$src" >/dev/null 2>&1; then
    rm -f "$tmp"; return 0
  fi
  echo "--- vendor: $f (new/changed) ---"
  [ -f "$dst" ] && diff <(tail -n +3 "$dst") "$src" | head -12 || echo "  (new file)"
  mv "$tmp" "$dst"; changed=$((changed+1))
}

for f in "${RTL[@]}"; do
  [ -f "$SRC/$f" ] || { echo "ERROR: missing $SRC/$f" >&2; exit 3; }
  vendor_one "$f"
done

# firmware hex: pure data (readmemh-parsed) -> no header stamp; copy verbatim on change.
if [ -f "$SRC/$HEX" ]; then
  if [ ! -f "$DST/$HEX" ] || ! diff -q "$SRC/$HEX" "$DST/$HEX" >/dev/null; then
    cp "$SRC/$HEX" "$DST/$HEX"; echo "--- vendor: $HEX (updated $(wc -l < "$DST/$HEX") lines) ---"; changed=$((changed+1))
  fi
else
  echo "WARN: $SRC/$HEX missing -- run ./build_firmware.sh to (re)generate it." >&2
fi

# (re)generate the qip so Quartus compiles the vendored RTL. The hex is found via a SEARCH_PATH
# entry added in nes_pocket.qsf during the M3 apply (see M3 checklist) -- not listed here.
QIP="$DST/copro.qip"
{
  echo "# AUTO-GENERATED by sync_to_pocket.sh from dr-mario-mods/fpga/copro @ ${HASH}. DO NOT EDIT."
  for f in "${RTL[@]}"; do
    case "$f" in *.sv) t=SYSTEMVERILOG_FILE ;; *) t=VERILOG_FILE ;; esac
    printf 'set_global_assignment -name %-18s [file join $::quartus(qip_path) "%s"]\n' "$t" "$f"
  done
} > "$QIP"

echo "OK: vendored ${changed} item(s) into $DST ; wrote $(basename "$QIP")"
